snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: zc57870.eu-central-1
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"

      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"

      warehouse: WH_ANALYTICS
      threads: 10

 
